name = "Gallery"
uuid = "857a3ff3-737a-4aba-a1f0-888341c4b54a"
repo = "git@github.com:AtelierArith/Gallery.git"
description = "Julia Registry of AtelirArith"

[packages]
b612f6cd-3a6e-4e62-9d6b-447ae96af911 = { name = "Kyulacs", path = "K/Kyulacs" }
