name = "Gallery"
uuid = "857a3ff3-737a-4aba-a1f0-888341c4b54a"
repo = "git@github.com:AtelierArith/Gallery.git"
description = "Julia Registry of AtelirArith"

[packages]
1f096619-141e-4d77-a13b-040156ae333b = { name = "PyPlotly", path = "P/PyPlotly" }
b612f6cd-3a6e-4e62-9d6b-447ae96af911 = { name = "Kyulacs", path = "K/Kyulacs" }
